name: C++ Tests

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Compile and run tests
      run: |
        cd test
        g++ -std=c++20 -o test test_mymath.cpp ../src/mymath.cpp
